import SwiftUI

/// Sovereign institutional color scheme for CLAD Signer
/// Colors are generated via Material You's Tonal Palette system (Material Kolor)
/// and shared between iOS and Android for 100% visual consistency
struct CladColors {

    // MARK: - Status Indicator Colors
    // These are semantic colors used for connection status dots

    /// Connected status - Emerald green
    static let statusConnected = Color(hex: 0x0A8C6B)

    /// Connecting status - Light gold
    static let statusConnecting = Color(hex: 0xD4A574)

    /// Disconnected status - Cool gray
    static let statusDisconnected = Color(hex: 0xA0AEC0)

    /// Error status - Red
    static let statusError = Color(hex: 0xDC3545)

    // MARK: - Material You Color Scheme
    // All colors below are generated by Material Kolor and shared via SKIE

    struct ColorScheme {
        let background: Color
        let surface: Color
        let primary: Color
        let onPrimary: Color
        let secondary: Color
        let onSecondary: Color
        let onBackground: Color
        let onSurface: Color
        let error: Color
        let tertiary: Color
        let onSurfaceVariant: Color
        let messageSent: Color
        let messageReceived: Color

        /// Returns adaptive color scheme computed from Material Kolor
        /// Colors are generated from charcoal seed using Material You algorithm
        /// Brand colors (muted gold, emerald green) are preserved
        static func forScheme(_ scheme: SwiftUI.ColorScheme) -> ColorScheme {
            return ColorAdapterIOS.getColorScheme(for: scheme)
        }
    }
}

// MARK: - Color Extension for Hex Support

extension Color {
    init(hex: UInt, alpha: Double = 1.0) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255.0,
            green: Double((hex >> 8) & 0xFF) / 255.0,
            blue: Double(hex & 0xFF) / 255.0,
            opacity: alpha
        )
    }
}
